---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common
data:
  deployment: "{{ deployment }}"
  project: "{{ project }}"
  gitlab_user: "{{ gitlab_user }}"
  slack_webhook_url: "{{ slack_webhook_url }}"
