---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: redis
  labels:
    service: redis
spec:
  selector:
    service: redis
  template:
    metadata:
      labels:
        service: redis
        name: redis
    spec:
      containers:
        - name: redis
          image: quay.io/fedora/redis-6
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: "/var/lib/redis/data"
              name: redis-pv
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "800Mi"
              cpu: "400m"
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
  replicas: 1
  strategy:
    type: Recreate
