# https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding
# oc describe rolebinding edit

---

kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: view
subjects:
- kind: ServiceAccount
  name: betka
roleRef:
  kind: ClusterRole
  name: view

---

kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: edit
subjects:
- kind: ServiceAccount
  name: betka
roleRef:
  kind: ClusterRole
  name: edit
