on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Run Tox tests on betka

jobs:
  tox_test:
    name: Tox test
    strategy:
      fail-fast: false
      matrix:
        tox_env: [py311, py312]
    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests on betka
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: gcc rpm-devel git python3-devel distgen nss_wrapper make python3-gitlab python3-pip python3-devel
